### ISSUE TITLE
ekinhbayar/IntervalParser breaking changes

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#105]
There have been breaking changes in https://github.com/ekinhbayar/IntervalParser.

When @ekinhbayar releases a new version we need to make at least `!!reminder` compatible again.

Do other things use it yet?

**Comment by ekinhbayar** [comment]
Pretty sure it was just used within reminder and only the normalizing method (which is now in Normalizer).

**Comment by DaveRandom** [comment]
@ekinhbayar I'm closing this issue because it's part of the reminder changes we were discussing before and can be incorporated in the eventual PR
