### ISSUE TITLE
Adding logic to Terminator

### ISSUE THREAD

**Issue by Nessworthy** [Room-11/Jeeves#109]
Hiya,

Say if I ask Jeeves a question which could produce an expected output based on a calculation, would that:

a) Fall into the scope of this plugin (Terminator) and
b) Be something that would be nice to have?

For example, a question like `Jeeves, do you like humans?`, if not predefined, could respond with something much like a magic 8-ball. where it picks an option randomly from a selection provided.

The main way I could think of doing that with the current plugin is to allow callbacks to be provided in the array of matches. The callback would be passed the original message and any captured groups, and would simply expect a string output.

That or some weird string syntax.

Thoughts?

**Comment by PeeHaa** [comment]
The scope of the plugin is to be able to act like a proper chatbot at some point.

Jeeves should be able to always respond in one way or another when pinging him.

I have been playing myself locally with the idea of adding search results into the mix to be able to respond to "Who is Tesla?" which would grab the first paragraph of wikipedia.

I could see random responses being used but I would love to see it try to respond in a sane manner whenever possible.

**Comment by DaveRandom** [comment]
Emphasis on "never possible"

**Comment by PeeHaa** [comment]
I have a [cleverbot implementation](https://github.com/PeeHaa/async-chatter-bot) which should serve as a nice fallback.

So this only will get triggered when none of the special cases in terminator match.

**Comment by DaveRandom** [comment]
Closing as implemented by cleverbot
