### ISSUE TITLE
`CodeFormat` plugins tends to confuse people / is too spammy

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#11]
I've seen a couple of code format messages from Jeeves yesterday where it resulted in a confused users instead of a nicely formatted code block.

The latest example was a post by Ekin which resulted in the following [edit history](http://chat.stackoverflow.com/messages/28425507/history):

```
Ekin
yst 9:59 PM
deleted this message

Ekin
yst 9:58 PM
edited: hey, would this fail somehow to unset the array before filling it? `unset($array); while($query->fetch())[ $array[] = $element; }

Ekin
yst 9:58 PM
edited: hey, would this fail somehow to unset the array before filling it? unset($array); while($query->fetch())[ $array[] = $element; }

Ekin
yst 9:57 PM
said: hey, would this fail somehow to unset the array before filling it? unset($array); while($query->fetch())[ $array[] = $element; }
```

Perhaps we should only let it trigger if the message starts with [php code keywords](https://github.com/Room-11/Jeeves/blob/master/src/Chat/Plugin/CodeFormat.php#L55-L60). This doesn't prevent all people from dumping unformatted code, but it also doesn't result in confused users trying to fix their messages in broken chat mark down.

Thoughts?

**Comment by pcrov** [comment]
Either give it an explicit trigger like `!!format` or cut it completely. Asking Jeeves to figure it out on his own is inevitably going to end up confusing or spammy.

Bots should speak when spoken to.

**Comment by WesNetmo** [comment]
considered that even if properly formatted some huge walls of code are really annoying to have in chat, i would suggest a radical solution
Jeeves could move the message to bin if it's poorly formatted / huge and could re-post it with proper formatting, or, he could pastebin it if it's very long

**Comment by pcrov** [comment]
Not sure I'm comfortable with giving the bot elevated privileges, or it automagically binning messages even if it had them.

**Comment by PeeHaa** [comment]
@pcrov related http://chat.stackoverflow.com/transcript/11?m=28409505#28409505

**Comment by kelunik** [comment]
I think we should disable it for now. The Javascript room has a similar thing in their bot.

**Comment by Danack** [comment]
> Bots should speak when spoken to.

Pretty much this. People posting ill formatted code isn't that big a problem.....having bots annoy people would be.

**Comment by Zvax** [comment]
I like the idea of room owners being able to trigger Jeeves formatting posts with !!format / !!pastebin postid.

That would need elevated powers for Jeeves though, which doesn't really seem scary. JS and CV rooms have those and it seems to go well. That being said, I'm not that much of a regular over there so maybe there *are* incidents.

**Comment by ralt** [comment]
For the record, we use [this](https://github.com/Zirak/SO-ChatBot/blob/master/source/plugins/unformatted-code.js) in the js room and it has worked fairly well. I haven't seen any false positive in the last 6 (?) months we've been using it. Sometimes some messages are missed, but it's fine.

**Comment by DaveRandom** [comment]
Closing because no-one really seems to care about this any more, feel free to complain if I am wrong about that.
