### ISSUE TITLE
Implement persistent storage

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#12]
It would be nice if the bots has some way to store data.

**Comment by Zvax** [comment]
here is a very basic file storage thing https://github.com/Zvax/Jeeves/commit/80aa446e5d1fe89ff3ba64ba874d588d1b4ed413

how bad is it?

**Comment by PeeHaa** [comment]
`E_TOO_MUCH_BLOCKING` :-)

Have a look at https://github.com/amphp/file and see if you can leverage it
