### ISSUE TITLE
Add !!man command

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#15]
[@Jeeves consider learning man /cc @PeeHaa](http://chat.stackoverflow.com/transcript/message/28738511#28738511).

I would say simply request `http://linux.die.net/man/1/scp`

**Comment by ralt** [comment]
How do you guess the `1` there though? :)

**Comment by PeeHaa** [comment]
I think `1` is the shell command and `2` is the C code.

**Comment by ralt** [comment]
Nope, these numbers are categories. You can have stuff in 1-8.

**Comment by pcrov** [comment]
Let the freebsd man pages guess - `https://man.freebsd.org/scp`

**Comment by PeeHaa** [comment]
Implemented using the freebsd site
