### ISSUE TITLE
Fix "what do you think about..." pattern 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#152]
http://chat.stackoverflow.com/messages/35334011/history
 Source - http://chat.stackoverflow.com/transcript/message/35334469#35334469

**Comment by DaveRandom** [comment]
@ekinhbayar @PeeHaa  please make this issue into something that explains what the problem actually is because I don't understand it

**Comment by ekinhbayar** [comment]
If there's a comma after the ping it doesn't work. Ie. `@Jeeves, what do you think about Laravel?" fails but without the comma it works.

**Comment by DaveRandom** [comment]
Fixed by https://github.com/Room-11/Jeeves/commit/a66d48628f871d4b2e5d037561f654ab8a2dd5c1
