### ISSUE TITLE
Request for !!conf(erences) command

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#164]
Source - http://chat.stackoverflow.com/transcript/message/35658217#35658217

**Comment by Nessworthy** [comment]
Reckon there's a good data source out there?
Closest I've found is http://lanyrd.com/topics/php/

**Comment by PeeHaa** [comment]
There is http://www.php.net/conferences/

**Comment by DaveRandom** [comment]
That page doesn't have the dates of the confs in any sane computer-readable format :-(

Without that it's probably not very useful

**Comment by DaveRandom** [comment]
@Nessworthy @PeeHaa I'm closing this for now on the grounds that I can see no practical way to implement it in a way that is actually useful. If someone comes up with something, feel free to re-open.
