### ISSUE TITLE
Add about command

### ISSUE THREAD

**Issue by Nessworthy** [Room-11/Jeeves#17]
Wouldn't be much about it. Just gives a brief sentence description about Jeeves, a link to its repo and its maintainer.

**Comment by kelunik** [comment]
`!!version` includes a link already. Maintainer is mainly @PeeHaa, but also other people from room 11.

**Comment by PeeHaa** [comment]
You're willing to implement it @Nessworthy?

Let me know. I can give you write access to the repo when needed.

**Comment by kelunik** [comment]
PRs can also be added without direct access. :-)

**Comment by Nessworthy** [comment]
Yeah, I'll write up a PR. Can take things from there. :)

**Comment by PeeHaa** [comment]
Awesome \o/

**Comment by DaveRandom** [comment]
This is basically what !!help with no args would do, so closing this in favour of #31
