### ISSUE TITLE
implement !!booze command

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#182]
Source - http://chat.stackoverflow.com/transcript/message/36010725#36010725

**Comment by DaveRandom** [comment]
ref http://chat.stackoverflow.com/transcript/11?m=35872400#35872400

**Comment by PeeHaa** [comment]
Implemented in https://github.com/Room-11/Jeeves/commit/29bb6d1f3a8ce3e0e962614e722bab636dc36bb5
