### ISSUE TITLE
Tweet Markdown 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#222]
Support chat markdown in tweets, either removing it or changing it to twitter equivalent.
 Source - http://chat.stackoverflow.com/transcript/message/37854801#37854801

**Comment by PeeHaa** [comment]
Just remove these calls (and the methods) https://github.com/Room-11/Jeeves/blob/master/src/Plugins/Tweet.php#L232-L233

**Comment by PeeHaa** [comment]
Fixed in https://github.com/Room-11/Jeeves/pull/240
