### ISSUE TITLE
tweet text as comics http://imgur.com/a/XFYpb

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#223]
Source - http://chat.stackoverflow.com/transcript/message/37886274#37886274

**Comment by JayPHP** [comment]
Separate plugin for !!quote to generate these images - Can then be tweeted as normal images.

**Comment by Netmosfera** [comment]
shrink text technique https://jsfiddle.net/em6ukdt5/ https://jsfiddle.net/em6ukdt5/1/

**Comment by PeeHaa** [comment]
I present you [the lib](https://github.com/PeeHaa/php-comic-generator).

Only need to create a plugin for it and handle the uploading of the images somewhere.

**Comment by PeeHaa** [comment]
Implemented in https://github.com/Room-11/Jeeves/commit/b89227708b38dd6771355d659a9e60eb2c4d1f1d
