### ISSUE TITLE
Add welcome command

### ISSUE THREAD

**Issue by krakjoe** [Room-11/Jeeves#23]
Welcome command, JS room has one ... like they are better than us or somethin' ...

**Comment by gooh** [comment]
what does it do?

**Comment by Zvax** [comment]
maybe something like !!welcome name

with jeeves responding with some basic fooness of the room

**Comment by PeeHaa** [comment]
The message could be made dynamic so we don't have to dick around in code just to change the welcome message

**Comment by krakjoe** [comment]
The JS room has one, just says "Welcome {user}, please read chat rules and be a cool person" basically ...

**Comment by ralt** [comment]
An important note: it doesn't do it for everyone. It does it after the first message of a user in the room (not when the user enters the room), and only if the user has less than 1000 reputation.

**Comment by krakjoe** [comment]
I saw someone do it on demand, that would be enough ... right ?

**Comment by ralt** [comment]
That's also possible yeah, if you want to link to rules and ask being nice...

**Comment by krakjoe** [comment]
That's more what I was thinking ... an automatic thing might be nice too ... but automated bots are scary ... what if they take over ?

**Comment by krakjoe** [comment]
I'm scared.

**Comment by DaveRandom** [comment]
Can now be done with !!alias and !!sayf.

Example:

`!!alias welcome sayf Welcome %p, please read the [Chat Guidelines](https://guide.room11.org/)`
`!!welcome bob`

Results in "Welcome @Bob, please read the [Chat Guidelines](https://guide.room11.org/)"
