### ISSUE TITLE
!!tweet repeats the protocol for images embedded in text

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#233]
Source - http://chat.stackoverflow.com/transcript/message/38788237#38788237

> attending interview with candidates for senior dev position https://i.imgur.com/nOb84Em.gif

That message will end up with the following tweet:

> attending interview with candidates for senior dev position https:https://i.imgur.com/nOb84Em.gif

**Comment by DaveRandom** [comment]
Fixed by https://github.com/Room-11/Jeeves/commit/efe405047f4422050be91f35565dee6bf875c91d

**Comment by Nessworthy** [comment]
Makes sense :P Was trying to test this yesterday and couldn't find anything wrong!
