### ISSUE TITLE
default blame arg 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#236]
Default blame to @PeeHaa
 Source - http://chat.stackoverflow.com/transcript/message/39370498#39370498

**Comment by PeeHaa** [comment]
It's an alias, not a command @JayPHP .

Not sure it's possible

**Comment by DaveRandom** [comment]
Not at the moment and I can't think of a sensible way to implement it using the current mechanism of an alias to `sayf`.

Obviously could easily be done with a plugin, though.
