### ISSUE TITLE
No feedback when stack exchange auth fails

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#253]
Posted by: @Nessworthy
Source: http://chat.stackoverflow.com/transcript/message/39661173#39661173

When using incorrect auth information in your config file, Jeeves should log some sort of error.
Currently, nothing is logged.

**Comment by Nessworthy** [comment]
Closing #253 as already fixed - Room11\OpenId's package will throw a `FailedAuthenticationException` when logging into SO fails.
