### ISSUE TITLE
!!horoscope doesn't work 

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#259]
I think the onion has taken the section down http://www.theonion.com/features/horoscope

New URL format e.g. is here: https://entertainment.theonion.com/your-horoscopes-week-of-october-17-2017-1819655153 (Thanks @ekinhbayar!)

Posted by: @Nessworthy
Source: http://chat.stackoverflow.com/transcript/message/39708549#39708549

**Comment by Zvax** [comment]
I'm too dumb to guess what the numbers in the url mean, so I just fetch the general page, then the specific horoscope, then extract the asked for horoscope.

There's no date range anymore, so I aggressively removed code. People better know what their signs are.

I'm pretty sure the ucfirst($sign) is fragile so please someone try to break it so I can make it more solid-er.

https://github.com/Zvax/Jeeves/tree/bugfix/onion-horoscope-change
