### ISSUE TITLE
Add wotd repin service

### ISSUE THREAD

**Issue by EleventyJeeves** [Room-11/Jeeves#268]
Posted by: @DaveRandom
Source: http://chat.stackoverflow.com/transcript/message/40691005#40691005

**Comment by DaveRandom** [comment]
WOTD produces a lot of spam. Rather the bot should have a service which fetches wotd once a day at a specific time and pins the message for the day.

That way we can disable/unmap the command endpoint and reduce the amount of repetitive spam.
