### ISSUE TITLE
wotd not displaying word correctly, provides link to dictionary.com

### ISSUE THREAD

**Issue by tiffany-taylor** [Room-11/Jeeves#279]
See message below:
https://chat.stackoverflow.com/transcript/message/43794475#43794475

**Comment by tiffany-taylor** [comment]
Nevermind, closing this. Appears to be an issue with dictionary.com's WOTD site.
https://www.dictionary.com/wordoftheday/

![image](https://user-images.githubusercontent.com/3333510/44947592-bbc93d80-add4-11e8-93c7-114941e2cc2b.png)

**Comment by Nessworthy** [comment]
Sent a message over through their contact form. Not sure if it's just a manual process 100% of the time and they've stopped updating it.
In the meantime, is there another WOTD source we can use?

**Comment by Nessworthy** [comment]
https://www.merriam-webster.com/word-of-the-day
and http://www.wordthink.com/

Are decent alternatives

**Comment by mega6382** [comment]
I've already created a PR for adding a default message. Tonight, I will also add another PR for using an alternative source in case the main doesn't work for WOTD. I believe https://www.merriam-webster.com/word-of-the-day is good, as @Nessworthy suggested.

**Comment by mega6382** [comment]
@tiffany-taylor @Nessworthy  Here is the pr for this https://github.com/Room-11/Jeeves/pull/281

**Comment by tiffany-taylor** [comment]
Closing as per @mega6382's request, and dictionary.com's fixing their WOTD page.
