### ISSUE TITLE
add !!reminder command

### ISSUE THREAD

**Issue by gooh** [Room-11/Jeeves#30]
Add a command to set reminders, e.g.

    Gordon: !!reminder 5m Grab some beer!

After 5 minutes, Jeeves will respond with

    @Gordon Grab some beer!

**Comment by DaveRandom** [comment]
The implementation of this is trivial, but it seems like the sort of thing that could be open to abuse...

Users shouldn't be using the chat room as a personal organiser anyway, so maybe restrict it to admin users?

**Comment by gooh** [comment]
I favor trusting our roomies first. I've seen reminders like this on IRC with no problems. Can still restrict it later if abused.
