### ISSUE TITLE
add !!plugin command

### ISSUE THREAD

**Issue by gooh** [Room-11/Jeeves#32]
Add a command to enable/disable/configure/list individual plugins, e.g.

    Gordon: !!plugin list
    Jeeves: {list of all plugins}

    Gordon: !!plugin status giphy
    Jeeves: Giphy is currently disabled

    Gordon: !!plugin enable giphy
    Jeeves: I can totally giphy now.

    Gordon: !!plugin configure image-type=still
    Jeeves: Setting image-type to still.

    Gordon: !!plugin disable giphy
    Jeeves: Ok, no more giphy, bro.

Trying to enable/disable an unknown plugin should result in something like this:

    Gordon: !!plugin enable doesnt-exist
    Jeeves: I dont know this plugin

Trying to configure an unknown setting should result in something like this:

    Gordon: !!plugin configure invalid=foo
    Jeeves: I dont know this setting. Try one of {list of valid settings}

Trying to enable/disable an already enabled/disabled plugin should simply give the regular response.
This command should be limited to admins obviously.
This command might make the !!help command redundant.

**Comment by DaveRandom** [comment]
Implemented list/enable/disable/status.

Plugin settings need addressing, but not via the !!plugin command as this is no good for API keys etc.
