### ISSUE TITLE
v2 wishlist

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#34]
List of things we want should we ever reach a v2 before getting bored with the project:
- [x] Add the ability for Jeeves to live in multiple rooms
- [ ] Instead of letting plugins post error messages themselves let them throw some exception instead so something higher up the chain can post the error message (need to check whether I still want/need this)
- [ ] Update readme

**Comment by DaveRandom** [comment]
Closed in favour of #176
