### ISSUE TITLE
Retrieve class methods

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#4]
Currently we only support `!!docs ClassName`. Also implement `!!docs ClassName::method` to retrieve method docs.

**Comment by kelunik** [comment]
This should be closed.

**Comment by PeeHaa** [comment]
Recent evidence suggest it should probably not:

> !!docs pdo::prepare

&nbsp;

> [ [pg_prepare](secure.php.net/manual/en/…) ] Submits a request to create a prepared statement with the 
given parameters, and waits for completion.

It's pretty buggy for some reason. As much as I would like to blame @DaveRandom it could very well be an error from me. Will investigate.

**Comment by kelunik** [comment]
Could as well be an SO parsing bug. :P

**Comment by PeeHaa** [comment]
git blame @DaveRandom 

`strtr` doesn't work like that. Fixed
