### ISSUE TITLE
Add !!undo

### ISSUE THREAD

**Issue by PeeHaa** [Room-11/Jeeves#52]
Implement `!!undo` command which delete either the last message of Jeeves (`!!undo`), deletes the last n message of Jeeves (`!!undo n`) or a specific message (`!!undo messageid`).

**Comment by kelunik** [comment]
Can it also delete a tweet again? :P

**Comment by PeeHaa** [comment]
It will only delete chat messages, but if you need / want drunk tweet protection I could probably implement something for !tweet as well.

**Comment by PeeHaa** [comment]
Now that I think about it we probably want plugins to have an undo method which undos whatever it is it has done cc @daverandom

**Comment by kelunik** [comment]
I don't think it's worth implementing it for all plugins. Every plugin would have to keep state of their actions. For plugins that only fetch information and post messages, we could handle that at a higher level. Deleting tweets or something like that obviously needs its own implementation.

**Comment by DaveRandom** [comment]
@kelunik we can have it work for plugins like this maybe:

1. user issues `!!undo <message link or id>`
1. fetch some info about the message (ID/content etc) and puts it into a VO.
1. delete the message
1. invoke `Plugin#onUndo($messageInfo): Promise` with a try/catch guard. Plugin may do any additional cleanup such as deleting a tweet, which it can figure out from the message info passed. A default implementation will be provided in `BasePlugin` which is just `return new Success;`

**Comment by PeeHaa** [comment]
It would be sexy if `!!giphy` does a move (to the gifbin) instead of a delete.

**Comment by DaveRandom** [comment]
@PeeHaa that could still work with a slight refactoring of the above, i.e. invoke `Plugin#onUndo()` first and make the default action cancellable

**Comment by DaveRandom** [comment]
Implemented as !!remove.

Deleting tweets is a separate issue that as yet has not been needed.
