### ISSUE TITLE
Have the rating, possibly a little description too, alongside the imdb result.

### ISSUE THREAD

**Issue by SaitamaSama** [Room-11/Jeeves#54]
See: http://chat.stackoverflow.com/transcript/message/29748612#29748612

Currently the result is something like:
`[ Zootopia ] 2016, Byron Howard...`

The rating of the movie, and possibly a lil' description would be a nice feature!

Cheers!

**Comment by PeeHaa** [comment]
What about something like:

• [The Avengers (2012)](http://www.imdb.com/title/tt0848228/) - Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mi… [♥ 8.1 | 🍅 4.9]
• [The Avengers (2012)](http://www.imdb.com/title/tt0848228/) - Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mi… [♥ 8.1 | 🍅 4.9]
• [The Avengers (2012)](http://www.imdb.com/title/tt0848228/) - Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mi… [♥ 8.1 | 🍅 4.9]
• [The Avengers (2012)](http://www.imdb.com/title/tt0848228/) - Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mi… [♥ 8.1 | 🍅 4.9]
• [The Avengers (2012)](http://www.imdb.com/title/tt0848228/) - Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mi… [♥ 8.1 | 🍅 4.9]

?

**Comment by gourabnagDev** [comment]
Looks nice to me! +1

**Comment by Nessworthy** [comment]
`cv-pls`
