### ISSUE TITLE
Add !!translate command

### ISSUE THREAD

**Issue by iroegbu** [Room-11/Jeeves#60]
Command that translates text from one language to another
```
Me: !!translate en de Speak Dutch to me
Jeeves:  Praat Nederlands met me
```
[working example](https://gist.github.com/iroegbu/c52219734895acc527540a0a649af326) hacked together. Consider doing away with the language is user is translating from, so:
```
Me: !!translate de Speak Dutch to me
Jeeves:  Praat Nederlands met me
```

**Comment by DaveRandom** [comment]
I was looking at this yesterday but gave up at the point of "totally cba getting an API key". Since you've provided one, I'll get right on it :-P
