### ISSUE TITLE
Add voting results to !!rfcs

### ISSUE THREAD

**Issue by staabm** [Room-11/Jeeves#67]
Show also the voting results when invoke !!rfcs

**Comment by kelunik** [comment]
Not `!!rfcs`, as that's for the pinned messages. Maybe `!!voting` or `!!rfc *`

**Comment by PeeHaa** [comment]
I think `!!voting` is the most clear one.

**Comment by Nessworthy** [comment]
How would this pick up which rfc you're on about? Would it try and guess the rfc you specify or only allow exact matches?

**Comment by Nessworthy** [comment]
Ah, just for reference this is already implemented in `!!rfc *`, can this issue be closed?

**Comment by Nessworthy** [comment]
`cv-pls` @DaveRandom
